<h3><b>Readme: </b></h3>
1. 'array' means numpy array data type: numpy.array()</br>
2. 'list' means python list data type: list()

We encourage you to explore more functionalities in 'Python for Data Analysis, 3E' by Wes McKinney, Chapter 4: 'NumPy Basics: Arrays and Vectorized Computation'.</br>
Link: https://wesmckinney.com/book/numpy-basics

In [1]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.6 MB 14.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 18.3 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 19.2 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 19.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 15.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

<h3><b>Task 1 </b></h3>

Create a python list in range 1_000_000. </br>
Then multiply each element by 2 and measure the execution time with the help of magic command %timeit.</br>
</p>


In [3]:
# Create a list with range 1_000_000
data = list(range(1_000_000))

# Measure execution time of multiplying each element by 2
%timeit [x * 2 for x in data]


40.3 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<h3><b>Task 2 </b></h3>
<p>
Now create a numpy array in range 1_000_000. </br>
Then multiply each element by 2 and measure the execution time.</br></br>
Then compare the multiplication execution time of numpy array and python list. Which one is faster?</br>
Do you have to use a for loop for the multiplication operation with numpy arrays?</br>
</p>


In [4]:
import numpy as np

# Create a NumPy array
data_np = np.arange(1_000_000)

# Measure execution time of multiplying each element by 2
%timeit data_np * 2


1.98 ms ± 88.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


<h3><b>Task 3 </b></h3>
<p>
Create a numpy array out of [1.5, -0.1, 3], [0, -3, 6.5]. Then do: </br>
1. Add each element to itself;</br>
2. Multiply each element by 10.</br>
3. How many dimentions does the array have? Use proper numpy attributes to return the answer.</br>

</p>


In [5]:
import numpy as np

# Create the array
arr = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

# Add each element to itself
added = arr + arr

# Multiply each element by 10
multiplied = arr * 10

# Get number of dimensions
dimensions = arr.ndim

# Print results
print("Original array:\n", arr)
print("\nEach element added to itself:\n", added)
print("\nEach element multiplied by 10:\n", multiplied)
print("\nNumber of dimensions:", dimensions)


Original array:
 [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Each element added to itself:
 [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]

Each element multiplied by 10:
 [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Number of dimensions: 2


<h3><b>Task 4 </b></h3>
<p>
Create an array of zeros in the following shape: </br>
[[0. 0. 0. 0. 0. 0.]</br>
 [0. 0. 0. 0. 0. 0.]</br>
 [0. 0. 0. 0. 0. 0.]]</br></br>
Hint: </br>
numpy.empty() serves a different purpose. It creates an array without initializing its values to any particular value, so it’s not safe to assume that it will return an array of all zeros. 
This function returns uninitialized memory and thus may contain nonzero "garbage" values. You should use this function only if you intend to populate the new array with data.




</p>


In [6]:
import numpy as np

# Create a 3x6 array filled with zeros
zeros_array = np.zeros((3, 6))

# Display the array
print(zeros_array)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


<h3><b>Task 5 </b></h3>
<p>
Create an array of ones in the following shape: </br>
[[1., 1.],</br>
 [1., 1.]]</br>





</p>


In [7]:
import numpy as np

# Create a 2x2 array filled with ones
ones_array = np.ones((2, 2))

# Display the array
print(ones_array)


[[1. 1.]
 [1. 1.]]


<h3><b>Task 6 </b></h3>
<p>
Create an array with shape(2, 2) where all values are equal to 10 </br>



</p>


In [8]:
import numpy as np

# Create a 2x2 array filled with the value 10
tens_array = np.full((2, 2), 10)

# Display the array
print(tens_array)


[[10 10]
 [10 10]]


<h3><b>Task 7 </b></h3>
<p>
Create an array in the following shape: </br>
[[1. 0. 0.]</br>
[0. 1. 0.]</br>
[0. 0. 1.]]</br>



</p>


In [9]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<h3><b>Task 8 </b></h3>
<p>
Create array out of numbers 1, 2, 3, 4, 5, then display its data type. </br>
Then convert the data type to float64 and display the data type.</br>



</p>


In [10]:
import numpy as np

# Create an array out of numbers 1,2,3,4,5
arr = np.array([1, 2, 3, 4, 5])
print("Original array data type:", arr.dtype)

# Convert the data type to float64
arr_float = arr.astype(np.float64)
print("Converted array data type:", arr_float.dtype)


Original array data type: int64
Converted array data type: float64


<h3><b>Task 9 </b></h3>
<p>
Create a python list in range of 100. </br>
Assign a scalar value of 1001 to the list elements with index 75, 76, 77, 78, 79, 80</br></br>


</p>


In [11]:
# Create a list with values from 0 to 99
my_list = list(range(100))

# Assign 1001 to elements at indices 75 to 80
for i in range(75, 81):
    my_list[i] = 1001

# Display the updated list slice to verify
print(my_list[70:85])


[70, 71, 72, 73, 74, 1001, 1001, 1001, 1001, 1001, 1001, 81, 82, 83, 84]


<h3><b>Task 10 </b></h3>
<p>
Now create a numpy array in range of 100. </br>
Assign a scalar value of 1001 to the array elements with index 75, 76, 77, 78, 79, 80</br></br>
Compare the assignment syntax with the one used with the python list.

</p>


In [12]:
import numpy as np

# Create a numpy array with values from 0 to 99
arr = np.arange(100)

# Assign 1001 to elements at indices 75 to 80
arr[75:81] = 1001

# Print the slice to verify
print(arr[70:85])


[  70   71   72   73   74 1001 1001 1001 1001 1001 1001   81   82   83
   84]


<h3><b>Task 11 </b></h3>
<p>
Create an array out of the following names: "Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe".</br>
Return a boolean array where 'True' indicates the position of 'Bob': </br>
Output result: [ True, False, False,  True, False, False, False]</br></br>
How would you do it if it was a python list?



</p>


In [13]:
import numpy as np

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

# Create boolean array where True means element is 'Bob'
bob_positions = (names == "Bob")

print(bob_positions)


[ True False False  True False False False]


<p>
What if you want to return a boolean array where 'True' indicates the position of 'Bob' or 'Will'?</br>

</p>


In [14]:
import numpy as np

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

# Boolean array where True if element is 'Bob' OR 'Will'
positions = (names == "Bob") | (names == "Will")

print(positions)


[ True False  True  True  True False False]


<h3><b>Task 12 </b></h3>
<p>
Create an integer array out of [4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4].</br>
Select values from the integer array where value in the names array is 'Bob' (see the previous tasks).</br>

</p>


In [15]:
import numpy as np

int_array = np.array([
    [4, 7],
    [0, 2],
    [-5, 6],
    [0, 0],
    [1, 2],
    [-12, -4],
    [3, 4]
])

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

selected_rows = int_array[names == "Bob"]
print(selected_rows)


[[4 7]
 [0 0]]


<p>
Run below piece of code and analyse the result:</br>




</p>


In [16]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])

[[7]
 [0]]
[7 0]


<h3><b>Task 13 </b></h3>
<p>
Create an array out of [4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4].</br>
Assign 0 to the values that are less then 0.</br>



</p>


In [17]:
import numpy as np

# Create the array
arr = np.array([
    [4, 7],
    [0, 2],
    [-5, 6],
    [0, 0],
    [1, 2],
    [-12, -4],
    [3, 4]
])

# Assign 0 to all elements less than 0
arr[arr < 0] = 0

print(arr)


[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


<h3><b>Task 14 </b></h3>
<p>
Create an array in range of 32 with shape(8, 4).</br>
1. Return the value of 4 using indexing.</br>
2. Return the value of 23 using indexing.</br>
3. Return the value of 29 using indexing.</br>
4. Return the value of 10 using indexing.</br>
5. Now using indexing, return the values of 4, 23, 29, 10 all together using one line of code</br></br>
Think of how would you do it using a python list and compare the syntax.

</p>


In [18]:
import numpy as np

arr = np.arange(32).reshape(8, 4)
print(arr)
print(arr[1, 0])  # Output: 4
print(arr[5, 3])  # Output: 23
print(arr[7, 1])  # Output: 29
print(arr[2, 2])  # Output: 10
indices = ([1, 5, 7, 2], [0, 3, 1, 2])
print(arr[indices])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
4
23
29
10
[ 4 23 29 10]


<h3><b>Task 15 </b></h3>
<p>
Create two arrays 'x' and 'y' with size 8 each populated with random float numbers with the help of numpy.random.standard_normal().</br>
1. Return the maximum value by comparing the two arrays.</br>
2. From array 'x', return an array containing the whole parts of the float, and another array containing the remainders. E.g. in float -0.60869751 whole part is -0, and remainder is -0.60869751</br>
</p>


In [19]:
import numpy as np

# Create two arrays x and y, each of size 8 with random floats
x = np.random.standard_normal(8)
y = np.random.standard_normal(8)

print("x:", x)
print("y:", y)

# 1. Return the maximum values comparing the two arrays element-wise
max_values = np.maximum(x, y)
print("\nElement-wise maximum values between x and y:")
print(max_values)

# 2. From x, get:
#    - the whole parts (integer parts) using np.trunc()
#    - the remainders by subtracting whole parts from x
whole_parts = np.trunc(x)
remainders = x - whole_parts

print("\nWhole parts of x:")
print(whole_parts)

print("\nRemainders of x:")
print(remainders)


x: [-0.16206747  0.32820066  0.22488205 -0.26865047 -0.98992091  0.31295173
  1.14542499  0.90968231]
y: [-0.05733484 -1.36605814 -1.58641495 -2.66206354 -0.40441114  1.79968465
 -0.16075453  2.1450122 ]

Element-wise maximum values between x and y:
[-0.05733484  0.32820066  0.22488205 -0.26865047 -0.40441114  1.79968465
  1.14542499  2.1450122 ]

Whole parts of x:
[-0.  0.  0. -0. -0.  0.  1.  0.]

Remainders of x:
[-0.16206747  0.32820066  0.22488205 -0.26865047 -0.98992091  0.31295173
  0.14542499  0.90968231]


<h3><b>Task 16 </b></h3>
<p>
Given below arrays, return a python list that takes a value from xarr whenever the corresponding value in cond is True, and otherwise takes the value from yarr.</br>
Use list comprehension technique and time it.</br></br>

Hint: this has multiple problems. First, it will not be very fast for large arrays (because all the work is being done in interpreted Python code). 
Second, it will not work with multidimensional arrays.</br>


</p>


In [21]:
xarr = np.random.standard_normal(1_000_000)
yarr = np.random.standard_normal(1_000_000)
cond = np.random.choice(a=[True, False], size=1_000_000)

<p>
Now repeat the previous task, but return a numpy array this time. Measure the execution time, and compare the results..</br>




</p>


In [22]:
import numpy as np
import time

# Create arrays
xarr = np.random.standard_normal(1_000_000)
yarr = np.random.standard_normal(1_000_000)
cond = np.random.choice(a=[True, False], size=1_000_000)

# 1. Using list comprehension and timing it
start_time = time.time()

result_list = [x if c else y for x, y, c in zip(xarr, yarr, cond)]

end_time = time.time()
list_time = end_time - start_time
print(f"List comprehension time: {list_time:.4f} seconds")

# 2. Using numpy.where and timing it
start_time = time.time()

result_np = np.where(cond, xarr, yarr)

end_time = time.time()
np_time = end_time - start_time
print(f"Numpy where time: {np_time:.4f} seconds")

# Confirm both results are the same (within floating precision)
print("Results are equal:", np.allclose(result_list, result_np))


List comprehension time: 0.0985 seconds
Numpy where time: 0.0020 seconds
Results are equal: True


<h3><b>Task 17 </b></h3>
<p>
What is a 'row' and what is a 'column' in a multidimensional array? </br></br>
Create an array using np.random.standard_normal with size(3, 5).</br>
1. Calculate the sum of each 'row'.</br>
2. Calculate the sum of each 'column'.</br>



</p>


In [24]:
import numpy as np

# Create array with shape (3, 5)
arr = np.random.standard_normal((3, 5))
print("Array:\n", arr)

# 1. Sum of each row (axis=1)
row_sums = arr.sum(axis=1)
print("\nSum of each row:")
print(row_sums)

# 2. Sum of each column (axis=0)
col_sums = arr.sum(axis=0)
print("\nSum of each column:")
print(col_sums)


Array:
 [[-0.7543277  -1.87756789 -0.60598238 -0.42990831  0.38596043]
 [-0.05475103  0.6820357   0.08044627 -1.34485786  0.39500376]
 [ 0.18520719  0.67804692 -1.16874082 -0.96336494  0.59415957]]

Sum of each row:
[-3.28182586 -0.24212317 -0.67469207]

Sum of each column:
[-0.62387155 -0.51748527 -1.69427693 -2.73813111  1.37512376]


<h3><b>Task 18 </b></h3>
<p>
Boolean values are coerced to 1 (True) and 0 (False). Thus, sum is often used as a means of counting True values in a Boolean array.</br>
1. Create an array using np.random.standard_normal with size 100.</br>
2. Return the count of values that are greater than zero and the count of values that are less or equal to zero.</br>

</p>


In [25]:
import numpy as np

# 1. Create array of 100 random floats
arr = np.random.standard_normal(100)

# 2. Count how many are > 0
count_gt_zero = np.sum(arr > 0)

# Count how many are <= 0
count_le_zero = np.sum(arr <= 0)

print(f"Count of values > 0: {count_gt_zero}")
print(f"Count of values <= 0: {count_le_zero}")


Count of values > 0: 51
Count of values <= 0: 49


<h3><b>Task 19 </b></h3>
<p>
Create an array using np.random.standard_normal with size(8, 10) and sort the values within each column.</br>




</p>


In [26]:
import numpy as np

# Create array with shape (8, 10)
arr = np.random.standard_normal((8, 10))
print("Original array:\n", arr)

# Sort values within each column (axis=0)
sorted_arr = np.sort(arr, axis=0)
print("\nSorted array (each column sorted):\n", sorted_arr)


Original array:
 [[ 9.12614841e-01 -7.57841827e-02 -4.49200294e-01 -1.17121839e+00
  -3.73777526e-01 -4.60524719e-01 -1.13535346e+00  1.43934936e+00
   2.52662940e-01 -7.58681227e-01]
 [ 4.76299051e-01 -2.12479453e-01 -1.19984264e+00 -1.60351455e+00
  -1.47364986e-02 -2.63369381e-01  1.17800432e+00 -3.04563293e-01
  -1.23788806e+00  3.11497858e-01]
 [-1.36772879e-01  3.09385725e+00 -5.12951574e-01  8.99803602e-01
   9.86925981e-01  1.44837949e+00 -2.16105415e+00 -1.08398286e+00
   4.23403210e-01 -1.19191299e+00]
 [-1.93008418e+00 -1.32022159e+00  4.41879014e-01  1.64871315e+00
  -2.25690253e+00 -1.30600001e-01  5.86355732e-01  1.07325863e+00
  -2.11914493e+00 -2.75066707e-01]
 [-5.43285522e-03  9.22470488e-02 -3.97922525e-01  2.29238850e-02
   5.66998307e-01 -5.13098544e-01  1.29624112e+00  2.61717675e-01
   2.80335013e-01  1.42859400e+00]
 [-9.66817400e-01  1.17495884e+00 -1.53174199e-01  7.90374100e-01
  -6.50028981e-01  7.31908320e-01 -1.79135423e+00  7.17863453e-02
  -4.80373061e-0

<h3><b>Task 20 </b></h3>
<p>
Create an array of names "Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe".</br>
Then return an array with unique value only.</br>




</p>


In [27]:
import numpy as np

names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

# Get unique values
unique_names = np.unique(names)
print(unique_names)


['Bob' 'Joe' 'Will']
